pipeline {
    agent any
    tools {
        maven 'Maven'
    }

     triggers {
          pollSCM('H/2 * * * *')
        }

    environment {
        GITHUB_TOKEN = credentials('github_manifest')
        DOCKERHUB_CREDENTIALS = credentials('enami_dockerhub')
        ARGO_CD_REPO = 'https://github.com/Khadija-Laamiri/e-banking-api-manifest.git'
        IMAGE_TAG = "v0.${BUILD_NUMBER}"
        APP_REGISTRY = "enamifatimazahrae2001/gateway"
        MANIFEST_FILE = "gateway-service/gateway-deployment.yml"
    }


    stages {
        stage('Build Artifact') {
                    steps {
                        script {
                            dir('api-gateway') {
                                sh 'mvn clean install'
                            }
                        }
                    }
                }

         stage('Build App Image') {
                    steps {
                        script {
                            dir('api-gateway') {
                                dockerImage = docker.build("${APP_REGISTRY}:${IMAGE_TAG}")
                            }
                        }
                    }
                }

        stage('Push to Docker Hub') {
                    steps {
                        withCredentials([usernamePassword(credentialsId: 'enami_dockerhub',
                                                          usernameVariable: 'DOCKERHUB_CREDENTIALS_USR',
                                                          passwordVariable: 'DOCKERHUB_CREDENTIALS_PSW')]) {
                            echo "Docker Username: ${DOCKERHUB_CREDENTIALS_USR}"

                            sh """
                                echo ${DOCKERHUB_CREDENTIALS_PSW} | docker login -u ${DOCKERHUB_CREDENTIALS_USR} --password-stdin
                                docker push ${APP_REGISTRY}:${IMAGE_TAG}
                                docker rmi ${APP_REGISTRY}:${IMAGE_TAG} -f
                            """
                        }
                    }
                }

        stage('Update Argo CD Manifest') {
            steps {
                dir('..') {
                    script {
                        withCredentials([string(credentialsId: 'github_manifest', variable: 'GITHUB_TOKEN')]) {
                                sh 'rm -rf e-banking-api-manifest'
                                sh """
                                    git clone https://oauth2:${GITHUB_TOKEN}@github.com/Khadija-Laamiri/e-banking-api-manifest.git
                                """

                            dir('e-banking-api-manifest') {
                                 sh """
                                    echo "Fichier manifest: ${MANIFEST_FILE}"
                                    sed -i "s|enamifatimazahrae2001/gateway:.*|enamifatimazahrae2001/gateway:${IMAGE_TAG}|" ${MANIFEST_FILE}

                                    git diff
                                    git add .
                                    git commit -m "Update api-gateway image version to ${IMAGE_TAG}"
                                    git push origin master
                                """
                            }
                            sh 'rm -rf e-banking-api-manifest'

                        }
                    }
                }
            }
        }
    }
}