package com.example.operators_api.web;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2025-01-06T21:56:02.912+01:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://web.operators_api.example.com/", name = "MarocTelecomSoapService")
@XmlSeeAlso({ObjectFactory.class})
public interface MarocTelecomSoapService {

    @WebMethod
    @RequestWrapper(localName = "recharge", targetNamespace = "http://web.operators_api.example.com/", className = "com.example.operators_api.web.Recharge")
    @ResponseWrapper(localName = "rechargeResponse", targetNamespace = "http://web.operators_api.example.com/", className = "com.example.operators_api.web.RechargeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String recharge(

        @WebParam(name = "collaboratorId", targetNamespace = "")
        java.lang.Long collaboratorId,
        @WebParam(name = "phoneNumber", targetNamespace = "")
        java.lang.String phoneNumber,
        @WebParam(name = "amount", targetNamespace = "")
        double amount
    );
}
