package com.example.operators_api.web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2025-01-06T21:56:02.995+01:00
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "MarocTelecomWS",
                  wsdlLocation = "file:/C:/Users/USER/Desktop/ensa/bankati/back/facture-service/src/main/resources/CustomerService.wsdl",
                  targetNamespace = "http://web.operators_api.example.com/")
public class MarocTelecomWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://web.operators_api.example.com/", "MarocTelecomWS");
    public final static QName MarocTelecomSoapServicePort = new QName("http://web.operators_api.example.com/", "MarocTelecomSoapServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/USER/Desktop/ensa/bankati/back/facture-service/src/main/resources/CustomerService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MarocTelecomWS.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/USER/Desktop/ensa/bankati/back/facture-service/src/main/resources/CustomerService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MarocTelecomWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MarocTelecomWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MarocTelecomWS() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MarocTelecomWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MarocTelecomWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MarocTelecomWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MarocTelecomSoapService
     */
    @WebEndpoint(name = "MarocTelecomSoapServicePort")
    public MarocTelecomSoapService getMarocTelecomSoapServicePort() {
        return super.getPort(MarocTelecomSoapServicePort, MarocTelecomSoapService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MarocTelecomSoapService
     */
    @WebEndpoint(name = "MarocTelecomSoapServicePort")
    public MarocTelecomSoapService getMarocTelecomSoapServicePort(WebServiceFeature... features) {
        return super.getPort(MarocTelecomSoapServicePort, MarocTelecomSoapService.class, features);
    }

}
