pipeline {
    agent any
    tools {
        maven 'Maven'
    }

    triggers {
        pollSCM('H/2 * * * *')
    }

    environment {
        GITHUB_TOKEN = credentials('github_manifest')
        DOCKERHUB_CREDENTIALS = credentials('enami_dockerhub')
        ARGO_CD_REPO = 'https://github.com/Khadija-Laamiri/e-banking-api-manifest.git'
        IMAGE_TAG = "v0.${BUILD_NUMBER}"
        APP_REGISTRY = "enamifatimazahrae2001/user"
        MANIFEST_FILE = "user-service/user-deployment.yml"
    }

    stages {
        stage('Build Artifact') {
            steps {
                script {
                    dir('user-service') {
                        bat "mvn clean install -DskipTests"
                    }
                }
            }
        }

        stage('Build App Image') {
            steps {
                script {
                    dir('user-service') {
                        dockerImage = docker.build("${APP_REGISTRY}:${IMAGE_TAG}")
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'enami_dockerhub',
                                              usernameVariable: 'DOCKERHUB_CREDENTIALS_USR',
                                              passwordVariable: 'DOCKERHUB_CREDENTIALS_PSW')]) {
                    echo "Docker Username: ${DOCKERHUB_CREDENTIALS_USR}"
                    writeFile file: 'docker_token.txt', text: "${DOCKERHUB_CREDENTIALS_PSW}"

                    bat """
                        docker login -u %DOCKERHUB_CREDENTIALS_USR% --password-stdin < docker_token.txt
                        docker push ${APP_REGISTRY}:${IMAGE_TAG}
                        docker rmi ${APP_REGISTRY}:${IMAGE_TAG} -f
                    """
                }
            }
        }

        stage('Update Argo CD Manifest') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'github_manifest', variable: 'GITHUB_TOKEN')]) {
                        // First, remove the directory if it exists
                        bat "if exist e-banking-api-manifest rmdir /S /Q e-banking-api-manifest"

                        // Then clone the repository
                        bat """
                            git clone https://oauth2:${GITHUB_TOKEN}@github.com/Khadija-Laamiri/e-banking-api-manifest.git
                        """

                        dir('e-banking-api-manifest') {
                            bat """
                                echo "Fichier manifest: ${MANIFEST_FILE}"
                                powershell "(Get-Content -Path '${MANIFEST_FILE}') -replace 'enamifatimazahrae2001/user.*', 'enamifatimazahrae2001/user:${IMAGE_TAG}' | Set-Content -Path '${MANIFEST_FILE}'"
                                git config --global user.email "jenkins@example.com"
                                git config --global user.name "Jenkins"
                                git diff
                                git add .
                                git commit -m "Update user service image version to ${IMAGE_TAG}"
                                git push origin master
                            """
                        }

                        // Clean up after pushing
                        bat "rmdir /S /Q e-banking-api-manifest"
                    }
                }
            }
        }
    }
}