name: Build and Deploy Microservices

on:
  push:
    branches:
      - master

jobs:
  filter:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      payment-transaction-changed: ${{ steps.filter.outputs.payment-transaction }}
      user-service-changed: ${{ steps.filter.outputs.user-service }}
      discovery-service-changed: ${{ steps.filter.outputs.discovery-service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Paths Filter
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters:
            payment-transaction:
              - 'service-payment-transaction/**'
            user-service:
              - 'user-service/**'
            discovery-service:
              - 'discoveryserver/**'

  payment-transaction-service:
    name: Build and Deploy Payment Transaction Service
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.payment-transaction-changed == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build, test, and deploy steps for payment-transaction-service
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run tests
        run: mvn test

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./service-payment-transaction
          tags: |
            laamirikhadija/payment-transaction-service:${{ github.sha }}
          push: true

      - name: Update manifest
        run: |
          git config --global user.email "khadija.laamiri19@gmail.com"
          git config --global user.name "khadija laamiri"
          sed -i "s#laamirikhadija/payment-transaction-service.*#laamirikhadija/payment-transaction-service:${{ github.sha }}#g" payment-transaction-service/payment-transaction-deployment.yml
          git add -A
          git commit -m "update payment-transaction-service image"
          git push origin master

  user-service:
    name: Build and Deploy User Service
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.user-service-changed == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build, test, and deploy steps for user-service
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run tests
        run: mvn test

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./user-service
          tags: |
            laamirikhadija/user-service:${{ github.sha }}
          push: true

      - name: Update manifest
        run: |
          git config --global user.email "khadija.laamiri19@gmail.com"
          git config --global user.name "khadija laamiri"
          sed -i "s#laamirikhadija/user-service.*#laamirikhadija/user-service:${{ github.sha }}#g" user-service/user-deployment.yml
          git add -A
          git commit -m "update user-service image"
          git push origin master

  discovery-service:
    name: Build and Deploy Discovery Service
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.discovery-service-changed == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build, test, and deploy steps for discovery-service
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run tests
        run: mvn test

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./discoveryserver
          tags: |
            laamirikhadija/discovery-service:${{ github.sha }}
          push: true

      - name: Update manifest
        run: |
          git config --global user.email "khadija.laamiri19@gmail.com"
          git config --global user.name "khadija laamiri"
          sed -i "s#laamirikhadija/discovery-service.*#laamirikhadija/discovery-service:${{ github.sha }}#g" discovery-service/discovery-deployment.yml
          git add -A
          git commit -m "update discovery-service image"
          git push origin master
