name: Build and Deploy Services

on:
  push:
    branches:
      - "payment-transaction-service"
      - "user-service"
      - "discovery-service"

jobs:
  build-payment-transaction-service:
    name: Build and Test Payment and Transaction Service
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/payment-transaction-service'
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run tests
        run: mvn test

  build-and-push-docker-image-payment:
    name: Build Docker Image and Push for Payment and Transaction Service
    runs-on: ubuntu-latest
    needs: build-payment-transaction-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push to DockerHub and GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./
          tags: |
            laamirikhadija/payment-transaction-service:${{ github.sha }}
          push: true

  update-manifest-payment:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image-payment
    steps:
      - name: Checkout manifest repository
        uses: actions/checkout@v3
        with:
          repository: Khadija-Laamiri/e-banking-api-manifest
          ref: master
          token: ${{ secrets.G_TOKEN }}

      - name: Setup Git Configuration
        run: |
          git config --global user.email "khadija.laamiri19@gmail.com"
          git config --global user.name "khadija laamiri"

      - name: Update manifest file
        run: |
          sed -i "s#laamirikhadija/payment-transaction-service.*#laamirikhadija/payment-transaction-service:${{ github.sha }}#g" payment-transaction-service/payment-transaction-deployment.yml
          git add -A
          git commit -am "Update image to ${{ github.sha }}"
      - run: git push origin master

  build-user-service:
    name: Build and Test User Service
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/user-service'
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run tests
        run: mvn test

  build-and-push-docker-image-user:
    name: Build Docker Image and Push for User Service
    runs-on: ubuntu-latest
    needs: build-user-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push to DockerHub and GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./
          tags: |
            laamirikhadija/user-service:${{ github.sha }}
          push: true

  update-manifest-user:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image-user
    steps:
      - name: Checkout manifest repository
        uses: actions/checkout@v3
        with:
          repository: Khadija-Laamiri/e-banking-api-manifest
          ref: master
          token: ${{ secrets.G_TOKEN }}

      - name: Setup Git Configuration
        run: |
          git config --global user.email "khadija.laamiri19@gmail.com"
          git config --global user.name "khadija laamiri"

      - name: Update manifest file
        run: |
          sed -i "s#laamirikhadija/user-service.*#laamirikhadija/user-service:${{ github.sha }}#g" user-service/user-deployment.yml
          git add -A
          git commit -am "Update image to ${{ github.sha }}"
      - run: git push origin master

  build-discovery-service:
    name: Build and Test Discovery Service
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/discovery-service'
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run tests
        run: mvn test

  build-and-push-docker-image-discovery:
    name: Build Docker Image and Push for Discovery Service
    runs-on: ubuntu-latest
    needs: build-discovery-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push to DockerHub and GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./
          tags: |
            laamirikhadija/discovery-service:${{ github.sha }}
          push: true

  update-manifest-discovery:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image-discovery
    steps:
      - name: Checkout manifest repository
        uses: actions/checkout@v3
        with:
          repository: Khadija-Laamiri/e-banking-api-manifest
          ref: master
          token: ${{ secrets.G_TOKEN }}

      - name: Setup Git Configuration
        run: |
          git config --global user.email "khadija.laamiri19@gmail.com"
          git config --global user.name "khadija laamiri"

      - name: Update manifest file
        run: |
          sed -i "s#laamirikhadija/discovery-service.*#laamirikhadija/discovery-service:${{ github.sha }}#g" discovery-service/discovery-deployment.yml
          git add -A
          git commit -am "Update image to ${{ github.sha }}"
      - run: git push origin master
